apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metranova-auth.fullname" . }}-token-store
  labels:
    {{- include "metranova-auth.labels" . | nindent 4 }}
    app.kubernetes.io/component: token-store
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "metranova-auth.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: token-store
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "metranova-auth.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: token-store
    spec:
      {{- include "metranova-auth.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "metranova-auth.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: token-store
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.tokenStore.image.repository }}:{{ .Values.tokenStore.image.tag }}"
          imagePullPolicy: {{ .Values.tokenStore.image.pullPolicy }}
          env:
            - name: LDAP_HOST
              value: {{ include "metranova-auth.fullname" . }}-openldap
            - name: LDAP_PORT
              value: "389"
            - name: LDAP_BASE_DN
              value: {{ include "metranova-auth.ldapBaseDN" . | quote }}
            - name: LDAP_BIND_DN
              value: "cn=admin,{{ include "metranova-auth.ldapBaseDN" . }}"
            - name: LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "metranova-auth.fullname" . }}-secrets
                  key: LDAP_ADMIN_PASSWORD
            - name: TOKEN_STORE_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "metranova-auth.fullname" . }}-secrets
                  key: TOKEN_STORE_ENCRYPTION_KEY
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.tokenStore.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
