apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: pipeline-user
  labels:
    strimzi.io/cluster: {{ .Values.cluster.name }}
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: metranova_flow
          patternType: literal
        operations:
          - Read
          - Write
          - Describe
          - DescribeConfigs
      - resource:
          type: topic
          name: metranova_snmp
          patternType: literal
        operations:
          - Read
          - Write
          - Describe
          - DescribeConfigs
      - resource:
          type: group
          name: metranova_pipeline
          patternType: literal
        operations:
          - Read
      - resource:
          type: cluster
        operations:
          - Describe
          - DescribeConfigs

