# Default SNMP input.
#
# Add targets by overriding this file, or by dropping additional .conf files into
# /etc/telegraf/telegraf.d (loaded automatically alongside telegraf.conf).
#
[[inputs.snmp]]
  agents = []
  timeout = "5s"
  version = 2
  community = "public"
  agent_host_tag = "device"
  interval = "60s"
  tags = { interval = "60", collector = "$HOSTNAME" }
