[[inputs.snmp]]
  agents = ["udp://agg1.lab-ncs55a1.testlab.grnoc.iu.edu:161"]
  timeout = "5s"
  version = 2
  community = "tstlb"
  agent_host_tag = "device"
  interval = "60s"
  tags = { interval = "60", agent_host = "156.56.6.124", collector = "$HOSTNAME" }

  [[inputs.snmp.table]]
    name = "snmp_if"

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifIndex"
      name = "oidIndex"
      is_tag = true

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifName"
      name = "name"

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifHCInOctets"
      name = "SNMP_IF-MIB::ifHCInOctets"

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifHCOutOctets"
      name = "SNMP_IF-MIB::ifHCOutOctets"

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifHCInBroadcastPkts"
      name = "SNMP_IF-MIB::ifHCInBroadcastPkts"

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifHCInMulticastPkts"
      name = "SNMP_IF-MIB::ifHCInMulticastPkts"

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifHCOutBroadcastPkts"
      name = "SNMP_IF-MIB::ifHCOutBroadcastPkts"

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifHCOutMulticastPkts"
      name = "SNMP_IF-MIB::ifHCOutMulticastPkts"

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifInErrors"
      name = "SNMP_IF-MIB::ifInErrors"

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifOutErrors"
      name = "SNMP_IF-MIB::ifOutErrors"

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifHCInUcastPkts"
      name = "SNMP_IF-MIB::ifHCInUcastPkts"

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifHCOutUcastPkts"
      name = "SNMP_IF-MIB::ifHCOutUcastPkts"

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifInDiscards"
      name = "SNMP_IF-MIB::ifInDiscards"

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifOutDiscards"
      name = "SNMP_IF-MIB::ifOutDiscards"

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifAdminStatus"
      name = "SNMP_IF-MIB::ifAdminStatus"

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifOperStatus"
      name = "SNMP_IF-MIB::ifOperStatus"
