apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metranova-api.fullname" . }}
  labels:
    {{- include "metranova-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "metranova-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metranova-api.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "metranova-api.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ include "metranova-api.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.adminApi.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path | quote }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path | quote }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          env:
            - name: ADMIN_API_HOST
              value: {{ .Values.adminApi.host | quote }}
            - name: ADMIN_API_PORT
              value: {{ .Values.adminApi.port | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.adminApi.logLevel | quote }}
            - name: ROOT_PATH
              value: {{ .Values.adminApi.rootPath | quote }}
            - name: CORS_REGEX
              value: {{ .Values.adminApi.corsRegex | quote }}
            - name: CLICKHOUSE_HOST
              value: {{ .Values.clickhouse.host | quote }}
            - name: CLICKHOUSE_PORT
              value: {{ .Values.clickhouse.port | quote }}
            - name: CLICKHOUSE_DB
              value: {{ .Values.clickhouse.database | quote }}
            - name: CLICKHOUSE_SECURE
              value: {{ .Values.clickhouse.secure | quote }}
            {{- if .Values.clickhouse.usernameKey }}
            - name: CLICKHOUSE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.clickhouse.secretName }}
                  key: {{ .Values.clickhouse.usernameKey }}
            {{- else }}
            - name: CLICKHOUSE_USERNAME
              value: {{ .Values.clickhouse.username | quote }}
            {{- end }}
            {{- if .Values.clickhouse.secretName }}
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.clickhouse.secretName }}
                  key: {{ .Values.clickhouse.passwordKey }}
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
