daemonize: false
pidfile: /tmp/nfacctd.pid

nfacctd_port: {{ .Values.nfacctd.port }}
nfacctd_ip: 0.0.0.0

plugin_pipe_zmq: true
plugin_pipe_zmq_profile: large

writer_id_string: nfacctd
timestamps_since_epoch: true
nfacctd_renormalize: true

pre_tag_map: /etc/pmacct/pretag.map

plugins: kafka[main]

kafka_topic[main]: {{ .Values.nfacctd.topic }}
kafka_config_file[main]: /etc/pmacct/kafka.csv
kafka_refresh_time[main]: 30

aggregate: peer_src_ip, label, src_host, dst_host, src_port, dst_port, proto, in_iface, out_iface, src_as, dst_as, peer_dst_ip, timestamp_start, timestamp_end, vlan
