security.protocol=ssl
ssl.ca.location=/etc/pmacct/cluster-ca/{{ .Values.kafka.clusterCaCert }}
ssl.certificate.location=/etc/pmacct/certs/{{ .Values.kafka.userCert }}
ssl.key.location=/etc/pmacct/certs/{{ .Values.kafka.userKey }}
{{- if .Values.kafka.keyPassword }}
ssl.key.password={{ .Values.kafka.keyPassword }}
{{- end }}
