bootstrap.servers={{ include "pmacct.kafkaBootstrapHost" . }}:{{ .Values.kafka.port }}
security.protocol=ssl
ssl.ca.location=/etc/pmacct/cluster-ca/{{ .Values.kafka.clusterCaCert }}
ssl.certificate.location=/etc/pmacct/certs/{{ .Values.kafka.userCert }}
ssl.key.location=/etc/pmacct/certs/{{ .Values.kafka.userKey }}
{{- if .Values.kafka.keyPassword }}
ssl.key.password={{ .Values.kafka.keyPassword }}
{{- end }}
queue.buffering.max.messages=500000
queue.buffering.max.kbytes=131072
batch.num.messages=10000
batch.size=1048576
linger.ms=10
compression.codec=snappy
request.required.acks=1
retries=5
retry.backoff.ms=100
debug=all
