apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telegraf-config
  labels:
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  telegraf.conf: |
{{ .Files.Get "configs/agent.conf" | trim | nindent 4 }}
{{- if .Values.outputs.kafka.enabled }}
{{ include "telegraf.kafkaOutputs" . | trim | nindent 4 }}
{{- end }}
{{- with .Values.outputs.extraConfig }}
{{ tpl . $ | trim | nindent 4 }}
{{- end }}
{{- if .Values.inputs.snmp.enabled }}
{{ .Files.Get "configs/input-snmp.conf" | trim | nindent 4 }}
{{- end }}
{{- if .Values.inputs.netflow.enabled }}
{{ .Files.Get "configs/input-netflow.conf" | trim | nindent 4 }}
{{- end }}
