{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-telegraf" .Release.Name) .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
