{{- if and .Values.grafana.enabled (.Values.grafana.admin.existingSecret) .Values.grafanaAdminSecret.create }}
{{- $secretName := .Values.grafana.admin.existingSecret -}}
{{- $userKey := default "admin-user" .Values.grafana.admin.userKey -}}
{{- $passwordKey := default "admin-password" .Values.grafana.admin.passwordKey -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $adminUser := .Values.grafanaAdminSecret.adminUser -}}
{{- $adminUserB64 := "" -}}
{{- if and (empty $adminUser) $existing (hasKey $existing.data $userKey) -}}
{{- $adminUserB64 = index $existing.data $userKey -}}
{{- else -}}
{{- if empty $adminUser -}}
{{- $adminUser = "admin" -}}
{{- end -}}
{{- $adminUserB64 = $adminUser | b64enc -}}
{{- end -}}
{{- $adminPassword := .Values.grafanaAdminSecret.adminPassword -}}
{{- $adminPasswordB64 := "" -}}
{{- if and (empty $adminPassword) $existing (hasKey $existing.data $passwordKey) -}}
{{- $adminPasswordB64 = index $existing.data $passwordKey -}}
{{- else -}}
{{- if empty $adminPassword -}}
{{- $adminPassword = randAlphaNum 32 -}}
{{- end -}}
{{- $adminPasswordB64 = $adminPassword | b64enc -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  {{ $userKey }}: {{ $adminUserB64 }}
  {{ $passwordKey }}: {{ $adminPasswordB64 }}
{{- end }}